version: '3.8'

services:
  license-server:
    build: .
    container_name: jetbrains-license-server
    ports:
      - "5000:5000"
    volumes:
      - license_data:/app/cache
      - license_logs:/app/logs
      - ./jetbrains_licenses.txt:/app/jetbrains_licenses.txt
    environment:
      - PYTHONUNBUFFERED=1
      - CACHE_DIR=/app/cache
      - LOG_FILE=/app/logs/fetcher.log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  license_data:
  license_logs:
